"""empty message

Revision ID: 35878cb6a38f
Revises: da2aa048bf32
Create Date: 2018-03-07 22:10:58.320220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35878cb6a38f'
down_revision = 'da2aa048bf32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highlight_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('highlight_post')
    # ### end Alembic commands ###
